config/routes.rb
Rails.application.routes.draw do
  root 'grades#index'
  resources :grades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:subject, :grade, :term, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= form_with(model: grade, local: true) do |form| %>
  <% if grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade %>
  </div>

  <div class="field">
    <%= form.label :term %>
    <%= form.text_field :term %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<img border="0" width="325" height="129" src="https://www.theworldsworstwebsiteever.com/index_files/image001.gif" align="left" alt="WHAT'S NEW" v:shapes="_x0000_s1027">


<%= render 'form', grade: @grade %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>


<img src="https://media3.giphy.com/media/4xpB3eE00FfBm/giphy.gif?cid=3640f6095c1ba0034e385a6877dda2b0" alt="baby success GIF" style="width: 480px; height: 458px; left: 0px; top: 0px; opacity: 1;">

app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>


<div class="row justify-content-md-center">
<h1 class="blinking headline text-danger large-text">Lovely Grades</h1>
</div>

<div class="row justify-content-md-center">
  <img class="text-center" src="https://media1.tenor.com/images/afc199aba63308be9826b60cfc574653/tenor.gif?itemid=8712171" alt="Резултат слика за yay">
</div>


<div class="row justify-content-md-center pt-4">


<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Grade</th>
      <th>Term</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td class="headline text-danger"><%= grade.subject %></td>
        <td ><%= grade.grade %></td>
        <td><%= grade.term %></td>
        <td><%= grade.date %></td>
        <td><%= link_to 'Show', grade %></td>
        <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
        <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
    <% end %>
  </tbody>
</table>

</div>


<div class="row justify-content-md-center pt-4">
        <%= link_to 'New Grade', new_grade_path %>
        <img height="20" src="https://www.theworldsworstwebsiteever.com/images/new21.gif" width="38">

        </div>

app/views/grades/new.html.erb
<img border="0" width="325" height="129" src="https://www.theworldsworstwebsiteever.com/index_files/image001.gif" align="left" alt="WHAT'S NEW" v:shapes="_x0000_s1027">

<%= render 'form', grade: @grade %>

<%= link_to 'Back', grades_path %>
<img class="irc_mi" src="https://media.giphy.com/media/13CoXDiaCcCoyk/giphy.gif" onload="typeof google==='object'&amp;&amp;google.aft&amp;&amp;google.aft(this)" width="400" height="332" style="margin-top: 54px;" alt="Резултат слика за wiggle cat gif">

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @grade.subject %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @grade.grade %>
</p>

<p>
  <strong>Term:</strong>
  <%= @grade.term %>
</p>

<p>
  <strong>Date:</strong>
  <%= @grade.date %>
</p>


<iframe width="560" height="315" src="https://www.youtube.com/embed/mVZFtS9rBgI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LovelyGrades</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="white-bg">
    <div class="container">
      <%= yield %>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>